### ISSUE TITLE
原项目（停止维护的）core.php正则存在错误

### ISSUE THREAD

**Issue by jizizr** [soxft/UrlShorter#1]
![image](https://user-images.githubusercontent.com/78908842/134517515-aefc4d9e-1880-4413-85f8-dab9e7ffeaf3.png)
更正为：
'#^(http|https)://(.+\\.)+[a-z]{2,}(/.\*)\*$#i'

**Comment by soxft** [comment]
原来的正则匹配出了什么问题？ 能不能给一个示例的网址呢？

**Comment by jizizr** [comment]
比如https://.gs这种无效域名是可以添加的

**Comment by jizizr** [comment]
github的编辑有点麻烦，自动都给我转义了，以图片上的正则表达为准哈

**Comment by soxft** [comment]
好的，已经替换了
