### ISSUE TITLE
Apache 伪静态如何写？

### ISSUE THREAD

**Issue by shangdev** [soxft/UrlShorter#5]
##rewrite apache create tool.apizl.com

RewriteRule '^/api/(.*)$' /api/main.php?method=$1 [L] 
RewriteRule '^/(.*)$' /index.php?short=$1 [L] 

我转换成以上好像不太行

**Comment by soxft** [comment]
```conf
location ~ ^/api {
    rewrite ^/api/(.*) /api/main.php?method=$1 last;
}

location ~ ^/ {
    if (!-e $request_filename) {
        rewrite ^/(.*) /index.php?short=$1 last;
    }
}
```

参考nginx的伪静态配置吧, 暂时没怎么用过Apache 所以不太清楚

**Comment by shangdev** [comment]
nginx伪静态好像不行，访问时打不开页面，用的xp环境

**Comment by soxft** [comment]
> nginx伪静态好像不行，访问时打不开页面，用的xp环境

nginx的伪静态是测试过的, 打不开页面提示什么呢

**Comment by shangdev** [comment]
是我写错了
