### ISSUE TITLE
提示: 系统错误, 请重试

### ISSUE THREAD

**Issue by MrZhongzq** [soxft/UrlShorter#9]
我已经按照要求配置了伪静态和数据库, 并且我看了数据库的log, 没有错误. 现在有点拿不准是哪里出的问题?

**Comment by lanhui672** [comment]
我也是这样

**Comment by soxft** [comment]
抱歉没有及时回复 ((((

在 api/config.php 中 启用 debug 模式后

应该可以在 F12 中看到详细的错误信息
